version: '3.1'

volumes:
  pg_db:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
